### ISSUE TITLE
Story for App

### ISSUE THREAD

**Issue by sian-codes** [sian-codes/androidApp#2]
Epic:

**Description**

To fully show that you have understood the lessons create a simple app in Kotlin using intelliJ or Android Studio

**Tasks**

- [] Task 1 - Come Up with a Simple App Design
- [] Task 2 - Come up with Simple Wireframes
- [] Task 3 - Create 3 valid User Reqs for the app
